name: vnlnet
dependencies:
  - python = 3.6 #python3
  - pytorch = 0.4.1 # pytorch 1.0 or 0.4.0 failed
  - numpy
  - imageio
  - tifffile
  - opencv
  - pyopencl # for NVIDIA GPU: cp /etc/OpenCL/vendors/nvidia.icd $CONDA_VIRTUALENV_PATH/etc/OpenCL/vendors/nvidia.icd
  - cython # read .pyx 
  - scikit-image # calculating recovery quality metrics (PSNR and SSIM)