name: dvp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - pytorch=1.2.0
  - jupyterlab
  - h5py
  - tifffile
  - tensorboardX
  - cython
  - scikit-image
  - scipy
  - pyopencl
  - ocl-icd-system
  - pip:
    - opencv-python

